language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install -e .[test]
  - python setup.py build_ext --inplace
script:
  - pytest --cov=aiosonic
after_success:
  coveralls
