trigger:
- master

strategy:
  matrix:
    Python36-ubuntu:
      python.version: '3.6'
      imageName: 'ubuntu-latest'

    Python37-ubuntu:
      python.version: '3.7'
      imageName: 'ubuntu-latest'

    Python36-macos:
      python.version: '3.6'
      imageName: 'macOS-latest'

    Python37-maOS:
      python.version: '3.7'
      imageName: 'macOS-latest'

    Python36-windows:
      python.version: '3.6'
      imageName: 'windows-latest'

    Python37-windows:
      python.version: '3.7'
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'

  - script: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      pip install -e ".[test]"
      pytest --cov=aiosonic -n auto
      coveralls
    displayName: 'Run tests'
