trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    Python35:
      python.version: '3.5'
    Python36:
      python.version: '3.6'

steps:
- script: |
    python -m pip install --upgrade pip setuptools wheel
    pip install -r requirements.txt
    pip install -e ".[test]"
    py.test -n auto
  displayName: 'Run tests'
